baseURL: "https://mpasierbski.com/"
languageCode: "en-us"
title: "Michal Pasierbski"
theme: "anubis"
paginate: 10
disqusShortname: "mpasierbski"
googleAnalytics: "UA-102108439-1"

menu:
  main:
    - identifier: archive
      name: Archive
      title: Archive
      url: /archives/
    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
    - identifier: about
      name: About me
      title: About me
      url: /about/

params:
  author: "Michal Pasierbski"
  description: "Software engineer's notebook"
  customCSS:
    - css/overrides.css

markup:
  goldmark:
    renderer:
      unsafe: true
    