baseURL: "//"
languageCode: "en-us"
title: "Michal Pasierbski"
theme: "anubis"
paginate: 10
disqusShortname: "mpasierbski"
googleAnalytics: "UA-102108439-1"

menu:
  main:
    - identifier: archive
      name: Archive
      title: Archive
      url: /archives/
    - identifier: cv
      name: CV
      title: CV
      url: https://pasierb.github.io/cv/
    