baseURL = "/"
languageCode = "en-us"
title = "mpasierbski"
theme = "beautifulhugo"
googleAnalytics = "UA-102108439-1"

[Params]
  logo = "/me.jpeg"
  subtitle = "Mostly about software engineering"
  rss = true

[Author]
  name = "Michal Pasierbski"
  github = "pasierb"
  linkedin = "mpasierbski"
  twitter = "mpasierbski"

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3

[[menu.main]]
  name = "CV"
  url = "https://pasierb.github.io/cv/"
  weight = 3