baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "mpasierbski"
theme = "beautifulhugo"
googleAnalytics = "UA-102108439-1"
disqusShortname = "mpasierbski"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  logo = "/me.jpeg"
  subtitle = "Mostly about software engineering"
  rss = true

# [[Params.bigimg]]
#  src = "me.jpeg"
#  desc = "Triangle"

[Author]
  name = "Michal Pasierbski"
  github = "pasierb"
  linkedin = "mpasierbski"
  twitter = "mpasierbski"

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3

[[menu.main]]
  name = "CV"
  url = "https://pasierb.github.io/cv/"
  weight = 3