[build]
  command = "hugo --minify --gc"
  publish = "public/"

[[redirects]]
  from = "/cv"
  to = "https://pasierb.github.io/cv/"
  force = true
  status = 301
  headers = {X-From = "Netlify"}

[context.production.environment]
HUGO_VERSION = "0.71.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.71.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.71.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.71.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"